name: abbon_mobile_test
description: "A new Flutter project."
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  copy_with:
    path: ./packages/copy_with
  go_router: ^14.8.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  uuid: ^4.5.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  app_settings: ^5.2.0
  easy_localization: ^3.0.7+1
  shared_preferences_foundation: ^2.5.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.5
  copy_with_gen:
    path: ./packages/copy_with_gen

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
