targets:
  $default:
    builders:
      data_model_gen:
        enabled: true
        generate_for:
          include:
            - example/*
      copy_with_gen:
        enabled: true
        generate_for:
          include:
            - example/*

builders:
#  data_model_gen:
#    target: ":data_model_gen"
#    import: "package:copy_with_gen/builder.dart"
#    builder_factories: [ "dataModel" ]
#    build_extensions: { ".dart": [ ".g.dart" ] }
#    runs_before:
#      - copy_with_gen
#    auto_apply: dependents
#    build_to: cache
#    applies_builders: [ "source_gen|combining_builder" ]
  copy_with_gen:
    target: ":copy_with_gen"
    import: "package:copy_with_gen/builder.dart"
    builder_factories: [ "dataModel", "copyWith"]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
